name: Deploy agenda
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download agenda
        run: curl -L "https://gist.githubusercontent.com/emilandin-afk/470b1e55469780d577350683ecbd985c/raw/agenda-pintura.html" -o agenda-pintura.html
      - name: Commit
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add agenda-pintura.html
          git commit -m "Update agenda from gist" || echo "No changes"
          git push
